### PR TITLE
modify the temp folder location 

### PR DESCRIPTION
**Pull request by Bin-Go2**
Using tempfile library to create the temporary folder

### CODE REVIEW

**Review by saggu — CHANGES_REQUESTED** [review]
Where is the code to delete the temp folder if user has specified to do so ? @Bin-Go2

**Comment by Bin-Go2** [comment]
```
if kwargs['retain_temporary_data'] == False:
    shutil.rmtree(kwargs['temporary_directory'])
```
between line 477~478

**Comment by saggu** [comment]
Looks good, for the final step, please delete any commented out code and not used imports

**Comment by Bin-Go2** [comment]
Let's message via slack

**Comment by saggu** [comment]
There are now conflicts in the file which has been updated since. Closing this PR

**Pull request closed without merging**
